### ISSUE TITLE
collection residues

### ISSUE THREAD

**Issue by BrenoCastroAlves** [PimpAPP/pimpapp-api#20]
RESIDUE
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 1,
            "latitude": null,
            "longitude": null,
            "photos": [],
            "materials": [
                {
                    "id": 1,
                    "created_on": "2017-03-24T18:33:17.420370Z",
                    "moderation_status": "P",
                    "mongo_hash": "",
                    "name": "Vidro",    
                    "description": "Vidro"
                },
                {
                    "id": 2,
                    "created_on": "2017-03-24T18:33:30.426923Z",
                    "moderation_status": "P",
                    "mongo_hash": "",
                    "name": "Residuo de contrução",
                    "description": "Residuo de contrução"
                }
            ],
            "description": "Residuo teste",
            "how_many_kilos": 500.0, 
            "user": 147
        }
    ]
}
```

FALTAM

- “address” - criar
- “user” é quem registrou o resíduo né? 
- tem que ter também “catador_active", que é quem está vindo pegar
- “catador_denied”, catador que aceitou e falhou/recusou

material [{
-  trocar "name" por “material”: 
- trocar "description" por “size”: variável 1 a 4
}]
-  “how many kilos” não precisa

// depois faremos o app dos catadores e eles, ao coletarem, vão avaliar o material, aí sim com mais propriedade sobre kg e material especifico ex plástico pvc 4. Só um heads up: os dados da coleta também serão alterados pelo catador

**Comment by Gpzim98** [comment]
1º “address” - criar
Já existia um campo na API para isso chamado reverse_geocoding é nele que se deve colocar a string com o endereço, inclusive o script que importa do banco de dados antigo já grava neste campo.

2º “user” é quem registrou o resíduo né?
Exato.

3º trocar "name" por “material”:
Não é uma boa prática ter um nome de atributo igual ao nome da classe, como a Classe já se chama material não é aconselhado repetir o nome em um atributo.

4º trocar "description" por “size”: variável 1 a 4 e “how many kilos” não precisa
Estou aguardando o resultado de sua conversa com o Vido sobre o que deve ser feito com relação a estas 2 alterações..

**Comment by Vido** [comment]
@BrenoCastroAlves 

Esta modelagem está correta, no geral.

Entenda que o Residue é uma oferta de residuo. A relação entre residuo e catador acontecem em outro Model do sistema. E Material é um m2m.

O único problema seria o how_many_kilos e o "size". Que está com problemas com relação a dependências funcionais. Vamos rever isso.
