### ISSUE TITLE
collection collect

### ISSUE THREAD

**Issue by BrenoCastroAlves** [PimpAPP/pimpapp-api#21]
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "pk": 1,
            "catador_confirms": false,
            "user_confirms": false,
            "active": true,
            "catador": 18,
            "residue": 1,
            "photo_collect_user": [
                {
                    "id": 5,
                    "created_on": "2017-03-24T18:55:07.388094Z",
                    "moderation_status": "P",
                    "mongo_hash": "",
                    "ppoi": "(0.5, 0.5)",
                    "full_photo": "http://127.0.0.1:8001/media/collects/postgres_ee2ymmB.png",
                    "author": 92,
                    "coleta": 1
                },
                {
                    "id": 6,
                    "created_on": "2017-03-24T18:55:21.207573Z",
                    "moderation_status": "P",
                    "mongo_hash": "",
                    "ppoi": "(0.5, 0.5)",
                    "full_photo": "http://127.0.0.1:8001/media/collects/levi.jpg",
                    "author": 92,
                    "coleta": 1
                }
            ],
            "photo_collect_catador": [
                {
                    "id": 3,
                    "created_on": "2017-03-24T18:54:44.731692Z",
                    "moderation_status": "P",
                    "mongo_hash": "",
                    "ppoi": "(0.5, 0.5)",
                    "full_photo": "http://127.0.0.1:8001/media/collect_catador/git_github.png",
                    "author": 1,
                    "coleta": 1
                },
                {
                    "id": 4,
                    "created_on": "2017-03-24T18:54:55.447778Z",
                    "moderation_status": "P",
                    "mongo_hash": "",
                    "ppoi": "(0.5, 0.5)",
                    "full_photo": "http://127.0.0.1:8001/media/collect_catador/postgres.png",
                    "author": 32,
                    "coleta": 1
                }
            ]
        }
    ]
}
```

"pk" > oq é?
"ppoi" > oq é?

porque tantas fotos aqui? a foto tirada pelo usuário vai em collection > residues e não aqui

aqui precisamos de infos da relação entre catador e gerador

"hour"
"day"
"catador_denied" > histórico de catadores negados.. ou aqui mantemos só os dados da ativa e mandamos isso para o collection >residues?

"address" já ta em collection > residue

tem uma outra demanda, que é o feedback. gerador vai poder dizer o que achou da coleta e catador vai poder dizer oq achou da coleta.

- seria algo assim -
deu certo > sim / não
porque > 6 botoes com opções pré programadas
conte a história > campo txt 

nao sei se entra aqui ou se criamos a collection > feedbacks

**Comment by Gpzim98** [comment]
1º "pk" > oq é?
PK é o mesmo que ID é o código identificador do registro.

2º "ppoi" > oq é?
Eu também não sei, este campo já existia no sistema quando eu comecei a trabalhar no projeto. No código a legenda dele esta como Primary Point of Interest (PPOI), e é um campo auxiliar ao campo de que faz upload de imagens no sistema. Aparentemente é um campo necessário para o funcionamento do plugin de imagem.

3º porque tantas fotos aqui? a foto tirada pelo usuário vai em collection > residues e não aqui
Não exatamente. A aplicação esta modelada para suportar fotos no Residue quando o gerador cria o Residue (Photo residues) e na Colleta tanto por parte do Catador (Photo collect catadors) quanto por parte do Gerador (Photo collect users)

Se você observar bem, no JSON da colleta isso fica claro, onde temos uma lista com as fotos incluidas na coleta pelo catador
 "photo_collect_catador": [
            {
                "id": 7,
                "created_on": "2017-03-24T18:51:53.867981Z",
                "moderation_status": "P",
                "mongo_hash": "",
                "ppoi": "(0.5, 0.5)",
                "full_photo": "http://localhost:8000/media/collect_catador/git_github.png",
                "author": 1,
                "coleta": 1
            }
        ]

e as fotos incluidas na coleta pelo gerador:
       "photo_collect_user": [
            {
                "id": 5,
                "created_on": "2017-03-24T18:41:51.026465Z",
                "moderation_status": "P",
                "mongo_hash": "",
                "ppoi": "(0.5, 0.5)",
                "full_photo": "http://localhost:8000/media/collects/levi.jpg",
                "author": 1,
                "coleta": 1
            }
        ]

4º aqui precisamos de infos da relação entre catador e gerador
Não entendi este item

5º "hour" << Não entendi
"day" << Não entendi
"catador_denied" > histórico de catadores negados.. ou aqui mantemos só os dados da ativa e mandamos isso para o collection >residues?

Não entendi o por que serai importante ter uma lista dos catadores que negaram uma coleta. A informação do catador ativo na colecta (como vc chamou na sua descrição), ou seja o que aceitou coletar o residuo já existe no JSON da coleta  "catador": 4, onde 4 é o código (id ou pk) do catador em questão

6º "address" já ta em collection > residue
Não encontrei este campo no JSON da colleta, talvez o mesmo já tenha sido removido.

7º tem uma outra demanda, que é o feedback. gerador vai poder dizer o que achou da coleta e catador vai poder dizer oq achou da coleta.

seria algo assim -
deu certo > sim / não
porque > 6 botoes com opções pré programadas
conte a história > campo txt
nao sei se entra aqui ou se criamos a collection > feedbacks

Hoje já existe a função de avaliar tanto o catador quanto a cooperativa, basicametne o usuário informa se o feedback é positivo, negativo ou neutro além de um comentário de texto. Essa foi a demanda que foi passada e desenvolvida. Caso queira que seja desenvolvido de acordo com essa descrição que você mandou, peço que discuta vom o Vido e definam o que precisa ser feito, mas acho que pelo tamanho da alteração não da mais tempo para este sprint.

**Comment by BrenoCastroAlves** [comment]
"hour" << Não entendi
"day" << Não entendi

collects registra a data e a hora da coleta marcada. é um acordo que catador e gerador fazem ao telefone e informam ao app esses numeros.


"catador_denied" > histórico de catadores negados.. ou aqui mantemos só os dados da ativa e mandamos isso para o collection >residues?

Não entendi o por que serai importante ter uma lista dos catadores que negaram uma coleta. A informação do catador ativo na colecta (como vc chamou na sua descrição), ou seja o que aceitou coletar o residuo já existe no JSON da coleta "catador": 4, onde 4 é o código (id ou pk) do catador em questão


é importante para o histórico dos catadores, para geração de dados. o usuário pode cancelar a coleta, o catador pode perder a coleta. Precisa ser implementado.
