### ISSUE TITLE
Recuperar informações sobre vários Catadores

### ISSUE THREAD

**Issue by Vido** [PimpAPP/pimpapp-api#3]
![PMCAPP](http://2014.desarrollandoamerica.org/wp-content/uploads/2014/07/Screencast3.png)

Eu imagino que não precisamos passar todos o dados.
Só precisamos do tipo (catador, coperativa, etc...), posição, nome, endereço.
Acho que isso já basta;

A API pode retornar tudo o que tem na base.
Depois precisamos pensar em algum tipo de filtro por posição.

```
/coleta/                               # Sem filtro, retorna tudo
/coleta/?type="coperativa" # Não temos nada isso
/coleta/?type="catador"
/coleta/?city="sao paulo"
```

**Comment by alexandre** [comment]
@Vido eu acho que precisamos estruturar a api antes. Ter a API não adianta muito sem o front.

O que nos dá tempo para trabalhar em um CRUD completo de catadores antes de partir para outra coisa.

[ ]'s

**Comment by Vido** [comment]
@alexandre É justamente o que estamos fazendo.
Eu estou me baseando pelos mockups.
Eles parecem ser bem completos.

Sim, o Front é importante. Mas não podemos misturar as coisas.
aqui no pimpapp-api vamos tratar da API.

Nós não temos bem definidos quais são os atributos dos catadores.
Eu acho mais lógico começar pelas consultas. Assim detectamos quais são os atributos relevantes.

**Comment by alexandre** [comment]
@Vido 

Eu concordo que são coisas separadas. Ainda assim, IMHO, terminar um CRUD + adicionar atributos depois é bem mais simples que fazer todas as consultas, adicionar campo, completar o CRUD.

De qualquer forma não deixa de ser uma abordagem valida. =]

[ ]'s

**Comment by Vido** [comment]
@alexandre,

Eu não penso em fazer todas as consultas possíveis.
Apenas as básica para podermos terminar um protótipo funcional.

Então atualmente temos esses campos: id, name, phone, address, latitude, longitude
Mas olhando pelo mockup, vamos precisar também:
- Fotos do catador
- Descrição do Perfil
- Tipo de material que ele recolhe
- Comentários

Temos quer ver como vamos gerenciar isso.
Se o catador é um usuário, ou se o catador é tipo uma wiki.

Mas para um protótipo eu acho que já está ok.

**Comment by Vido** [comment]
Migrado #1
