### ISSUE TITLE
Reestruturação de código de Flask para Django 1.8.5

### ISSUE THREAD

**Issue by viniarck** [PimpAPP/pimpapp-api#5]
Issue destinada para as seguintes atividades de migração:

Python 2.7 -> Python 3.4;
Flask -> Django 1.8.5.

Vou iniciar esta atividade neste fim de semana que é 31 de Outubro.

**Comment by Vido** [comment]
Eu diria que não é bem uma migração. Na verdade é um joga-fora-e-faz-outro.

O que pode ser aproveitado:
https://github.com/PimpAPP/pimpapp-api/blob/master/app/models.py
https://github.com/PimpAPP/pimpapp-api/tree/master/data

A missão aqui é:
- [x] Criar um virtualenv (pyvenv34)
- [x] Instalar os pacotes com o pip (django, django-restfull, etc...)
- [x] Criar e commitar o requirements.txt (pip freeze > requirements.txt) 
- [x] Criar o projeto em django (django-admin startproject)
- [x] Criar o app catadores e migrar o Model e fixtures antigos (manage.py startapp)

Com isso feito: o pessoal do Issue #1 pode começar a fazer as API-Views.

**Comment by alexandre** [comment]
@Vido e @viniciusarcanjo um detalhe: o projeto já está usando Python3.

**Comment by alexandre** [comment]
E como o @Vido comentou, a ideia pelo visto é escrever outro mesmo. =]

**Comment by viniarck** [comment]
Ok @Vido e @alexandre. @Vido estou seguindo estes checkboxes, previsao de conlusao neste fds agora (31/10).

Obs: estou mudando o titulo para melhor refletir a issue.

**Comment by viniarck** [comment]
Fiz uma solicitacao de um pull request para esta issue, poderiam verificar?
