### ISSUE TITLE
URGENT Vanished Catadores

### ISSUE THREAD

**Issue by BrenoCastroAlves** [PimpAPP/pimpapp-api#51]
![photo_2017-07-03_13-28-45](https://user-images.githubusercontent.com/1775189/27814156-0ec96488-6051-11e7-8b47-50ec8a72747e.jpg)

**Comment by BrenoCastroAlves** [comment]
Greg reported a conflict in the loading, which is only asking for the user´s location and not the catadore´s location

**Comment by Gpzim98** [comment]
Yes. There is a loader running when the Home page opens, but when the load finished running it doesn't get the information from the API as it was before.

**Comment by BrenoCastroAlves** [comment]
now the pins are showing but the profile of each catador is not. this is still urgent.
